### ISSUE TITLE
Tree types

### ISSUE THREAD

**Issue by bhousel** [rapideditor/temaki#87]
The latest id-tagging-schema switched the tree icons to use the `roentgen-tree` icon
https://github.com/openstreetmap/id-tagging-schema/pull/956

<img width="400" alt="Screenshot 2023-08-23 at 2 36 37 PM" src="https://github.com/rapideditor/temaki/assets/38784/2d4d172a-5313-4cb9-87ba-6acaf87eff80">

I don't think these look very good - so I'd like make sure all the leaf types have better icons in temaki, so we can override this.

https://wiki.openstreetmap.org/wiki/Key:leaf_type
- broad leaved
- needle leaved
- leafless (aka cactus)
- palm (apparently this got deprecated without any replacement and is still widely used?)

**Comment by tordans** [comment]
Oh, I just wanted to suggest this. 

Another great Icon would be a split-tree half broad leaved half needle leaved to to use as a "generic tree" for the base-preset of just `natural=tree`.

> …so we can override this.

I am all for updating the existing preset.

> palm (apparently this got deprecated without any replacement and is still widely used?)

Yeah, was confused by this but did not have the energy to dive into the topic. I hoped at some point someone would clarify the tagging in the wiki…

**Comment by tordans** [comment]
Thanks @bhousel those look good. However, I am not sure they will solve the current styling issue in iD/Rapid. I see the issue there as one with the "unspecified type". But we cannot update this preset with the broadleave icon since it will look the same as the more specific icon. And we need a solution for the map pin icon so the `?`-badge would be a big(ger) change on that one. So for now I don't see a direct follow up to improve https://github.com/openstreetmap/id-tagging-schema/pull/956 until we have a "unspecified" or half-half-tree.

Something like <img width="434" alt="image" src="https://github.com/rapideditor/temaki/assets/111561/e811ba2e-d02c-41a2-883e-0e5ef6badc49"> but for broad-neelde-leaved.

---

On the palm tree: I added https://github.com/openstreetmap/id-tagging-schema/issues/1034 to track this. I think some work needs to be done there first, before we can add a preset.

On the cactus: I could not find anything on the wiki nor on the forum. Fascinating, how biased the information is… :)

**Comment by bhousel** [comment]
I guess I could just make an icon of a tree with no leaves (branches only) and people could tag the leaf type if they want to?  

I am assuming that most trees don't have leaf type tagging right now, so this would be an icon that would be shown pretty frequently?

**Comment by tordans** [comment]
> I guess I could just make an icon of a tree with no leaves (branches only) and people could tag the leaf type if they want to?

I like the idea to use the icon without leaves as proxy for unspecified tree type! It will look nice and give a strong indicator to add the (right) leaves.

I always considered the skeleton icon to be reserved for a dead tree, but I guess we are a long way from adding this to our popular tagging practices ([13 uses](https://taginfo.openstreetmap.org/tags/dead%3Anatural=tree#overview), [7 uses](https://taginfo.openstreetmap.org/tags/natural=dead_tree#overview))

> I am assuming that most trees don't have leaf type tagging right now, so this would be an icon that would be shown pretty frequently?

Yes, the current slim tree icons is visible all the time…
https://taginfo.openstreetmap.org/tags/natural=tree#combinations
- 44_000_000 trees
- 4_000_000 leave_type

**Comment by bhousel** [comment]
> Ah, you did this already

haha yes!  I made that yesterday and published v5.6.
I actually really don't like how it turned out, and will probably rework it a bit and release a v5.6.1 patch, but we can start using it now.

**Comment by bhousel** [comment]
haha - icon still needs work 🙈 

<img width="916" alt="Screenshot 2023-10-26 at 5 21 08 PM" src="https://github.com/rapideditor/temaki/assets/38784/7a7de346-8e61-4355-9040-7f3d282ae8f1">

**Comment by bhousel** [comment]
I adjusted the tree icons today, they're looking a bit clearer at 15px now.

### before
<img width="898" alt="Screenshot 2023-12-28 at 4 46 47 PM" src="https://github.com/rapideditor/temaki/assets/38784/4325ab3d-eb96-451e-af9c-95f9b12b1b63">


### after
<img width="897" alt="Screenshot 2023-12-28 at 4 48 23 PM" src="https://github.com/rapideditor/temaki/assets/38784/76506195-a75f-4a92-a010-81b92fd963d8">


&nbsp;
&nbsp;

Drawing small icons is very challenging!  The trick is to remove as much detail as possible, but then exaggerate whatever details remain and try to make them fit to the pixel grid so that the details are visible and not too muddy.

&nbsp;
&nbsp;

Here's how the trees look around a golf course:

### broad leaved
<img width="1143" alt="Screenshot 2023-12-28 at 4 33 08 PM" src="https://github.com/rapideditor/temaki/assets/38784/cf5229b3-c2f0-4cb4-9f35-21789b0b478d">

### needle leaved
<img width="1111" alt="Screenshot 2023-12-28 at 4 31 14 PM" src="https://github.com/rapideditor/temaki/assets/38784/0612b73a-3a76-4c09-97e2-8b93c1320169">

### palm
<img width="1065" alt="Screenshot 2023-12-28 at 4 29 36 PM" src="https://github.com/rapideditor/temaki/assets/38784/e9f94e78-ef8b-4078-895f-6de772a18ab7">

### cactus
<img width="1136" alt="Screenshot 2023-12-28 at 4 37 40 PM" src="https://github.com/rapideditor/temaki/assets/38784/c11a9d77-c31e-4a58-b1bb-3174d0c21284">

### no leaves
<img width="1007" alt="Screenshot 2023-12-28 at 4 25 53 PM" src="https://github.com/rapideditor/temaki/assets/38784/d6b5e037-92af-49d0-b8c1-787e80452e00">
